condense_wildcard_suffixes     =  true
fn_empty_single_line           =  false
format_strings                 =  true
impl_empty_single_line         =  false
imports_indent                 =  "Block"
imports_layout                 =  "Vertical"
max_width                      =  150
normalize_comments             =  true
reorder_imported_names         =  true
reorder_imports_in_group       =  true
reorder_imports                =  true
report_fixme                   =  "Always"
report_todo                    =  "Always"
single_line_if_else_max_width  =  0
struct_lit_multiline_style     =  "ForceMulti"
struct_lit_width               =  0
struct_variant_width           =  0
take_source_hints              =  true
use_try_shorthand              =  true
wrap_comments                  =  true
